
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLOCK CONN_MSG CRYPTO_MSG DAY DIR FLAGS IFCONFIG_END IP IP_PROTOCOL IP_RNG LIB_VER_MSG MONTH OPEN_VPN_MSG PEER PLUGIN_MSG ROUTE_GATEWAY ROUTE_HEADER SBIN_IP_MSG SIGTERM_MSG SLASH SPECIAL_CHAR SYS_MSG TCP_MSG TUN_TAP_MSG VAR_SET VAR_VAL VPN_IP WEEK_DAY YEAR\n    main_rule : route_identifiers main_rule\n              | log_line main_rule\n              | log_line\n              | empty\n    \n    log_line : date PLUGIN_MSG DIR VAR_SET VAR_VAL\n              | date SBIN_IP_MSG IP IP_RNG\n              | date TUN_TAP_MSG\n              | date SBIN_IP_MSG IP PEER IP\n              | date SIGTERM_MSG \n              | date OPEN_VPN_MSG MONTH DAY YEAR\n              | date LIB_VER_MSG DAY MONTH YEAR LIB_VER_MSG\n              | date SYS_MSG\n              | date PLUGIN_MSG DIR SPECIAL_CHAR SPECIAL_CHAR DIR SPECIAL_CHAR FLAGS SPECIAL_CHAR VAR_SET VAR_VAL\n              | date CRYPTO_MSG\n              | date ROUTE_GATEWAY IP SLASH IP VAR_SET VAR_VAL VAR_SET VAR_VAL\n              | date SBIN_IP_MSG DAY DAY\n              | date SBIN_IP_MSG IP IP_RNG PEER IP\n              | date IP_PROTOCOL\n              | date CONN_MSG VAR_SET VAR_VAL VAR_SET VAR_VAL\n              | date TCP_MSG \n              | date SYS_MSG SPECIAL_CHAR VAR_SET VAR_VAL VAR_SET VAR_VAL\n              | date CONN_MSG VAR_SET IP VAR_SET VAR_VAL SPECIAL_CHAR VAR_SET VAR_VAL\n              | date IFCONFIG_END\n              | date SYS_MSG VAR_SET VAR_VAL VAR_SET VAR_VAL\n    \n    date : WEEK_DAY MONTH DAY CLOCK YEAR\n          | WEEK_DAY MONTH DAY CLOCK\n    route_identifiers : ROUTE_HEADER key_value_list ROUTE_HEADERkey_value_list : key_value_list key_value\n                      | key_valuekey_value : VPN_IP IPempty :'
    
_lr_action_items = {'ROUTE_HEADER':([0,2,3,10,11,15,16,19,20,22,24,25,27,28,29,42,44,53,56,57,66,67,69,71,74,81,82,84,],[5,5,5,27,-29,-7,-9,-12,-14,-18,-20,-23,-27,-28,-30,-6,-16,-5,-8,-10,-17,-11,-24,-19,-21,-15,-22,-13,]),'$end':([0,1,2,3,4,8,9,15,16,19,20,22,24,25,27,42,44,53,56,57,66,67,69,71,74,81,82,84,],[-31,0,-31,-3,-4,-1,-2,-7,-9,-12,-14,-18,-20,-23,-27,-6,-16,-5,-8,-10,-17,-11,-24,-19,-21,-15,-22,-13,]),'WEEK_DAY':([0,2,3,15,16,19,20,22,24,25,27,42,44,53,56,57,66,67,69,71,74,81,82,84,],[7,7,7,-7,-9,-12,-14,-18,-20,-23,-27,-6,-16,-5,-8,-10,-17,-11,-24,-19,-21,-15,-22,-13,]),'VPN_IP':([5,10,11,28,29,],[12,12,-29,-28,-30,]),'PLUGIN_MSG':([6,52,64,],[13,-26,-25,]),'SBIN_IP_MSG':([6,52,64,],[14,-26,-25,]),'TUN_TAP_MSG':([6,52,64,],[15,-26,-25,]),'SIGTERM_MSG':([6,52,64,],[16,-26,-25,]),'OPEN_VPN_MSG':([6,52,64,],[17,-26,-25,]),'LIB_VER_MSG':([6,52,58,64,],[18,-26,67,-25,]),'SYS_MSG':([6,52,64,],[19,-26,-25,]),'CRYPTO_MSG':([6,52,64,],[20,-26,-25,]),'ROUTE_GATEWAY':([6,52,64,],[21,-26,-25,]),'IP_PROTOCOL':([6,52,64,],[22,-26,-25,]),'CONN_MSG':([6,52,64,],[23,-26,-25,]),'TCP_MSG':([6,52,64,],[24,-26,-25,]),'IFCONFIG_END':([6,52,64,],[25,-26,-25,]),'MONTH':([7,17,34,],[26,33,46,]),'IP':([12,14,21,38,43,49,55,],[29,31,37,51,56,61,66,]),'DIR':([13,54,],[30,65,]),'DAY':([14,18,26,32,33,],[32,34,39,44,45,]),'SPECIAL_CHAR':([19,30,41,65,72,77,],[35,41,54,73,76,80,]),'VAR_SET':([19,23,30,35,48,50,51,59,61,75,76,80,],[36,38,40,47,60,62,63,68,70,78,79,83,]),'IP_RNG':([31,],[42,]),'PEER':([31,42,],[43,55,]),'VAR_VAL':([36,38,40,47,60,62,63,68,70,78,79,83,],[48,50,53,59,69,71,72,74,75,81,82,84,]),'SLASH':([37,],[49,]),'CLOCK':([39,],[52,]),'YEAR':([45,46,52,],[57,58,64,]),'FLAGS':([73,],[77,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'main_rule':([0,2,3,],[1,8,9,]),'route_identifiers':([0,2,3,],[2,2,2,]),'log_line':([0,2,3,],[3,3,3,]),'empty':([0,2,3,],[4,4,4,]),'date':([0,2,3,],[6,6,6,]),'key_value_list':([5,],[10,]),'key_value':([5,10,],[11,28,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> main_rule","S'",1,None,None,None),
  ('main_rule -> route_identifiers main_rule','main_rule',2,'p_main_rule','parser.py',257),
  ('main_rule -> log_line main_rule','main_rule',2,'p_main_rule','parser.py',258),
  ('main_rule -> log_line','main_rule',1,'p_main_rule','parser.py',259),
  ('main_rule -> empty','main_rule',1,'p_main_rule','parser.py',260),
  ('log_line -> date PLUGIN_MSG DIR VAR_SET VAR_VAL','log_line',5,'p_log_line','parser.py',268),
  ('log_line -> date SBIN_IP_MSG IP IP_RNG','log_line',4,'p_log_line','parser.py',269),
  ('log_line -> date TUN_TAP_MSG','log_line',2,'p_log_line','parser.py',270),
  ('log_line -> date SBIN_IP_MSG IP PEER IP','log_line',5,'p_log_line','parser.py',271),
  ('log_line -> date SIGTERM_MSG','log_line',2,'p_log_line','parser.py',272),
  ('log_line -> date OPEN_VPN_MSG MONTH DAY YEAR','log_line',5,'p_log_line','parser.py',273),
  ('log_line -> date LIB_VER_MSG DAY MONTH YEAR LIB_VER_MSG','log_line',6,'p_log_line','parser.py',274),
  ('log_line -> date SYS_MSG','log_line',2,'p_log_line','parser.py',275),
  ('log_line -> date PLUGIN_MSG DIR SPECIAL_CHAR SPECIAL_CHAR DIR SPECIAL_CHAR FLAGS SPECIAL_CHAR VAR_SET VAR_VAL','log_line',11,'p_log_line','parser.py',276),
  ('log_line -> date CRYPTO_MSG','log_line',2,'p_log_line','parser.py',277),
  ('log_line -> date ROUTE_GATEWAY IP SLASH IP VAR_SET VAR_VAL VAR_SET VAR_VAL','log_line',9,'p_log_line','parser.py',278),
  ('log_line -> date SBIN_IP_MSG DAY DAY','log_line',4,'p_log_line','parser.py',279),
  ('log_line -> date SBIN_IP_MSG IP IP_RNG PEER IP','log_line',6,'p_log_line','parser.py',280),
  ('log_line -> date IP_PROTOCOL','log_line',2,'p_log_line','parser.py',281),
  ('log_line -> date CONN_MSG VAR_SET VAR_VAL VAR_SET VAR_VAL','log_line',6,'p_log_line','parser.py',282),
  ('log_line -> date TCP_MSG','log_line',2,'p_log_line','parser.py',283),
  ('log_line -> date SYS_MSG SPECIAL_CHAR VAR_SET VAR_VAL VAR_SET VAR_VAL','log_line',7,'p_log_line','parser.py',284),
  ('log_line -> date CONN_MSG VAR_SET IP VAR_SET VAR_VAL SPECIAL_CHAR VAR_SET VAR_VAL','log_line',9,'p_log_line','parser.py',285),
  ('log_line -> date IFCONFIG_END','log_line',2,'p_log_line','parser.py',286),
  ('log_line -> date SYS_MSG VAR_SET VAR_VAL VAR_SET VAR_VAL','log_line',6,'p_log_line','parser.py',287),
  ('date -> WEEK_DAY MONTH DAY CLOCK YEAR','date',5,'p_date','parser.py',293),
  ('date -> WEEK_DAY MONTH DAY CLOCK','date',4,'p_date','parser.py',294),
  ('route_identifiers -> ROUTE_HEADER key_value_list ROUTE_HEADER','route_identifiers',3,'p_route_identifiers','parser.py',299),
  ('key_value_list -> key_value_list key_value','key_value_list',2,'p_key_value_list','parser.py',303),
  ('key_value_list -> key_value','key_value_list',1,'p_key_value_list','parser.py',304),
  ('key_value -> VPN_IP IP','key_value',2,'p_key_value','parser.py',308),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',312),
]
