
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CARNET CIPHER CLOCK CN_SET COLON CONN_MSG CRYPTO_MSG DAY DIR FASE_END FLAGS IFCONFIG_END IP IP_PROTOCOL IP_RNG LIB_VER_MSG MONTH OPEN_VPN_MSG PEER PLUGIN_MSG POOL_RET PORT PROF ROUTE_FLAG ROUTE_GATEWAY ROUTE_HEADER SBIN_IP_MSG SENT_CNT SIGTERM_MSG SLASH SPECIAL_CHAR SYS_MSG TCP_MSG TOPOLOGY TUN_TAP_MSG VAR_SET VAR_VAL VPN_IP WEEK_DAY YEARroute_identifiers : ROUTE_HEADERkey_value : VPN_IP IP'
    
_lr_action_items = {'ROUTE_HEADER':([0,],[2,]),'$end':([1,2,],[0,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'route_identifiers':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> route_identifiers","S'",1,None,None,None),
  ('route_identifiers -> ROUTE_HEADER','route_identifiers',1,'p_route_identifiers','mvp.py',251),
  ('key_value -> VPN_IP IP','key_value',2,'p_key_value','mvp.py',259),
]
